### ISSUE TITLE
Clarify if direction is mandatory, or not

### ISSUE THREAD

**Issue by aaime** [stac-api-extensions/sort#10]
In the openapi.yml file, we have the following:

```
    sortby:
      type: array
      description: |
        An array of objects containing a property name and sort direction.
      minItems: 1
      items:
        type: object
        required:
          - field
          - direction
        properties:
          field:
            type: string
          direction:
            type: string
            default: asc
            enum:
              - asc
              - desc
```

On one side, the ``direction`` field is marked as mandatory, but then it's also given a default value that will never be used.
What was the intention here?
