### ISSUE TITLE
Align Sort extension with DRAFT OGC API - Records - Part 1: Core

### ISSUE THREAD

**Issue by philvarner** [stac-api-extensions/sort#3]
https://docs.ogc.org/DRAFTS/20-004.html#sorting-parameter-sortby

Primary issue is the "sortables" endpoint.

**Comment by aaime** [comment]
In addition to sortables, the schema for sortby is different, it's a plain list of strings, mimicking the GET syntax:

https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/ogcapi-records-1-building-blocks.yaml#L113

```
    sortby:
      name: sortby
      in: query
      required: false
      schema:
        type: array
        minItems: 1
        items:
          type: string
          pattern: '[+|-]?[A-Za-z_].*'
```
